FROM mcr.microsoft.com/vscode/devcontainers/python:3

# Install any additional dependencies here
# RUN apt-get update && apt-get install -y <package-name>

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog